### ISSUE TITLE
Составить ER-диаграмму сущностей в системе

### ISSUE THREAD

**Issue by Reversean** [libsl-storage/wiki#7]

**Comment by m-maliarenko** [comment]
# Аналитика и структура БД

## Функции системы

- Хранение спецификаций и метаданных
- Хранение профилей пользователей
- Хранение политики прав доступа пользователей
- Поиск, агрегация и выдача спецификаций по критериям
- Агрегация и выдача данных спецификации
- Учёт версий спецификации

## Сущности и атрибуты

**Пользователь** - пользователь системы хранения спецификаций

- Имя учётной записи (username)
- Имя пользователя
- Адрес электронной почты
- Пароль
- Аватар

**Системная роль** - класс прав доступа пользователя на уровне системы

- Уровень доступа: пользователь, суперпользователь

**Право доступа** - право доступа к спецификации и директории

- Уровень доступа: чтение, изменение, удаление

**Спецификация** - спецификация библиотеки независимо от версии

- Название
- Описание
- Текст на языке LibSL
- Абстрактный синтаксический граф ASG

**Директория** - родительский узел спецификации для группировки

- Название

**Тег** - ярлык спецификации, который показывает, например, к какой прикладной области принадлежит данная библиотека или на какиех языках существуют реализации

- Название

**Тип тега** - классификация тегов по типу

- Название

**Конечный автомат** - конечноавтоматное представление спецификации или её части

- Название
- Описание (состояния, переходы и т.д.)
- Локальные переменные

## Связь сущностей и объектов

### ER-диаграмма

![libsl_storge_db_er](https://user-images.githubusercontent.com/71351680/234391933-235e63db-f0dd-4574-b5a6-a0f2dccf14f6.png)

### Пояснение

- **Системная роль** *присвоена* множеству **пользователей**
- **Пользователь** может *создавать и удалять* множество **спецификаций** на основании своей **системной роли**
- **Пользователь** может *создавать и удалять* множество **директорий** на основании своей **системной роли**
- **Пользователь** *имеет* **право доступа** на конкретную **спецификацию** и **директорию**
- Множество **спецификации** *содержится* в **директории** (В том числе и в особой корневой директории)
- Множество **пользователь** *просматривают* и *изменяют* множество **спецификаций** и **директорий** в соответствии со своим **правом доступа** к конкретной **спецификации** и **директории**
- **Спецификация** *помечена* множеством **тэгов**
-  Каждый **тег** имеет единственный **тип тега**
- Каждая **спецификация** _описывается_ множеством **конечных автоматов** (КА)
